trigger:
 paths:
   include:
   - kubernetes/myapp
   
pool:
  vmImage: "Windows-Latest"

stages:
- stage: deploy
  jobs:
  - deployment: d1
    environment: 'anonymous21155demofrontend'
    strategy:
     runOnce:
       deploy:
         steps: 
         - checkout: self
         - script: |
             echo "Listing contents of kubernetes/myapp:"
             dir "$(Build.SourcesDirectory)\
         - task: KubernetesManifest@1
           inputs:
             action: 'deploy'
             connectionType: 'azureResourceManager'
             azureSubscriptionConnection: 'myConnectionString'
             azureResourceGroup: 'RG-44'
             kubernetesCluster: 'gokulakscluster'
             namespace: 'default'
             manifests: |
               $(Build.SourcesDirectory)/kubernetes/myapp/deployment.yml
               $(Build.SourcesDirectory)/kubernetes/myapp/service.yml
             imagePullSecrets: 'mysecret'